version: "3.7"
services: 
  redis-master1:
    image: redis:5.0.7
    ports: 
      - "6379:6379"
    networks: 
      redis-master:
    # volumes: 
    #   - redisdata1:/data
networks:
    redis-master: 
volumes: 
    redisdata1:
      name: redisdata1
