= 个人简历

== 基本信息

* 姓名：谢非
* 性别：男
* 工作年限：8年
* 现住址：温江大学城
* 邮箱：280755491@qq.com
* 电话: 19981220172


== 自我介绍

* 8年工作经验，不同程度管理经验5年
* 对100人以上团队项目有过多项目、多次实际主导与管理经验
* 对分布式、微服务、DevOps、数据库方面基于领域驱动及ITIL理论结合有自己方法
* 熟悉容器化，并能应用到实际中，下降公司成本
* 熟悉云厂商架构，可从多方面提升公司应用稳定性、并下降成本
* 重构经验丰富，主导过多次重构
* 善于帮助他人、在多个技术群担任管理员


[plantuml]
....
@startmindmap
+ 架构

++ 系统架构
+++ 服务器
+++ 网络
+++ 数据库

++ 软件架构
+++ 高可用
+++ 高性能
+++ 微服务
+++ 容器化

++ 数据架构
+++ 数据库设计
+++ 数据分析
+++ 数据变现
@endmindmap
....

[plantuml]
....
@startmindmap

+ 管理
++ 部门管理
+++ 人事
+++ 绩效
+++ 人效

++ 研发管理
+++ 进度
+++ 质量
++ 成本控制
@endmindmap
....

[plantuml]
....
@startmindmap
+ DevOps
++ 语言
+++ JAVA
+++ C#
+++ NodeJs

++ 数据库
+++ MySql
+++ Redis
+++ ClickHouse
+++ Mongodb
+++ ElasticSearch

++ 数据优化

++ CMDB
++ CI/CD

++ 容器化
+++ docker
+++ kubernetes

++ 网络
+++ CLB
+++ CDN
+++ 交换机、路由器

@endmindmap
....

[plantuml]
....
@startmindmap
+ 商务
++ 第三方合作洽谈


@endmindmap
....


== 微服务相关
[plantuml]
....
skinparam componentStyle rectangle
component 微服务架构{
    component 网络 as network{
        [内部网关]
        [web服务器]
    }
    component 应用 as application{
        [前端]
        [后端服务]
    }
    network <-down---> application
    component 中间件 as middleware{
        [消息队列]
        [分布式锁]
        [分布式事务]
        [日志记录]
        [服务聚合]
        [任务调度]
        [链路追踪]
        [配置中心]
        [认证、权限中心]
        [注册发现]
        [日志记录] -- [链路追踪] : 特殊格式日志
        [日志记录] -- [监控报警] : 服务运行状态日志 
    }
    middleware <-up---> application
    component 数据库 as db{
        [OLAP] 
        [OLTP] 
        [缓存]
        [大数据]
        [OLTP] --> [OLAP]
        [OLTP] --> [缓存]
        [OLTP] --> [大数据]
    }
    application <-left--> db
    db <-down--> middleware
}
....

<<<
   
[plantuml]
....
component 微服务能力{
    component 高可用 as ha{
        [熔断]
        [限流]
        [告警]
        [恢复]
        [读写分离]
        [故障自愈]
        [负载均衡]
        [监控报警]
        [蓝绿]
        [灰度]
    }

    component 基础能力 as base{
        [容器化]
        [服务编排]
        [领域驱动]
        [CI/CD]
    }
    ha <-right-> base
}
....


== 工作经历

[plantuml]
....
@startuml

participant "奥沙科技" as A
participant "名门汇" as B
participant "二次元" as C
participant "译迅科技" as D
participant "指掌天下" as E
[-> A : 个人创业

A -> B: 实习结束
note over A
主营:网关、
数据安全、
大数据平台
endnote

B -> C : 因病离开
note over B
主营:家具行业
定制ERP
endnote

C -> D :不能承受\n连续几个月907
note over C
主营:看漫画APP
高峰时期千万日活
endnote

D -> E:业务发展瓶颈\n在我离职不久\n公司开始大量裁员
note over D
主营:翻译软件
endnote

E ->] : 与个人发展不符合
note over E
主营:
基于企业微信的
供应链解决方案
(CRM、订货商城
、ERP连接器、
新零售)
endnote

@enduml
....

* 2020年-10月--至今           成都指掌天下网络科技有限公司
** 职务：基础架构部门负责人
** 工作内容：
. 负责数据架构层设计、优化
. 负责系统架构设计、优化
. 对平台稳定性负责
. 管理公司运维、数据、安全部门
. 部门人员招聘
** 工作成绩
. 入职一个月获得公司--总裁特别奖
. 入职2周调整数据库，让应用平稳应对双十一
. 半年时间让公司项目稳定性获取巨大提升，入职前几乎天天报故障,现在稳定高效运行

* 2018年-10--2020年-10月    四川译迅科技有限公司
** 工作内容：
. 主导项目重构
. 负责数据库设计
. 对数据中心API性能负责
. 管理数据中心
** 工作成绩：
. 三个多用时间，重构项目让项目更稳定
. 2个多月时间重构数据层，让数据支撑更稳定

* 2017年-05--2018年10月  成都二次元动漫有限公司
** 工作内容：
. 代码审查与重构
. 程序性能优化
. 负责数据库设计，并创建数据中心

* 2016年1月--2017年4月    成都名门汇信息技术有限公司
** 工作内容：
. 引入分布式、缓存（传统项目中无相应实施，引入后加大服务的处理能力）
. 重构项目代码（定制代码规范，统一团队代码风格）
. 新人招聘与培训、项目文档建立与管理


== 主要项目


* 2020年10月--至今  架构部门管理

** 项目背景：
. 线上数据库管理与使用不合理
. 代码框架选择差异过大
. 运维人员能力跟不上公司发展
. 部分软件架构实现不合理

** 角色：架构部门负责人

** 内容：
. 带领所有项目组优化现有系统，提升现有架构稳定性
. 创建重构团队将.NET 重构为JAVA
. 加强团队数据思维
. 运维侧引入ITIL思维
. 人员招聘与培训

** 总结：
. 我的加入，项目比之前更稳定，事故越来越少，运转越来越高效
. 这是我第一次真正主导一个部门，在这之前做技术管理，也仅仅是在技术方面，在这里部门里的人事、技术等各个方面都需要自己考虑，对我是一个不小的挑战
. 学习了ITIL4，让自己管理水平得到了提升
. 全局PDCA这一套玩的比之前更流畅，之前的PDCA因角色局限，这次是在全局上有更好的提升
. 与云厂商谈判，将费用下降40%



* 2018年10月--2020年10月  数据中心建立
** 项目背景：
. 给业务层提供高质量API
. 调整现有数据结构以适应数据量的增长
. 公司数据架构设计与日常代码审查

** 角色：高级研发工程师

** 内容：

. 数据仓库建立
. 数据中心服务提供
. 数据库容器化
. 数据结构定义及数据库优化


** 总结：
. 提升微服务应用能力
. 强化设计理念
. 磨练自己心性，在此感谢领导对我的帮助。在为人处事方面不再以前那样激进。


* 2018年7--2018年8月 产品管理与广告管理系统

** 项目背景：
. 将所有产品通过统一后台管理
. 解决之前新加入广告就修改代码等不稳定因素
. 将三方广告、内部广告统一管理


** 角色：技术负责人

** 内容：

. 制定程序架构、数据库设计、接口定制
. 代码审核与重构
. 团队协调（20人以上）
. 提升微服务应用能力
. 强化设计理念

* 2018年1月--2018年4月   社区系统
** 项目背景：增加用户间互动交流，提升用户粘性。

** 角色：技术负责人
** 内容：
. 制定程序架构、数据库设计、接口定制
. 代码审核与重构
. 团队协调（20人以上）
. 为应用提供稳定的社区系统，增加用户粘性
** 总结：
. 提升工作中法律意识
. 提升多部门配合能力
. 提升微服务架构设计能力
. 第一次主导微服务架构设计

* 2017年10月--2017年11月 任务系统 
** 项目背景：为用户提供奖励获取通道，培养用户的收费意识，将应用走免费转向收费的一个重大规划。
 

** 角色：项目负责人
** 内容：
. 制定程序架构、数据库设计、接口定制
. 代码审核与重构
. 团队协调（20人以上）
. 为用户提供稳定的任务完成机制
. 在千万日活、QPS高峰时超过10万情况下，解决奖品领取问题
. 提升高并发、大数据处理能力
. 提升架构设计与实践能力
. 这是第一次处理高请求、高并发

* 2016年6月--2016年12月 梦天集团ERP开发与升级 
** 项目背景：
. 为集团提供加盟商下单功能 
. 提供拆单功能 
. 提供报价功能 
. 提供各种报表 
. 提供财务功能 
. 提供OA功能 
. 提供各种打印格式 
. 页面权限功能控制 


** 角色：开发组长
** 内容：
. 将项目变为分布式部署 （非容器化）
. 数据库优化 （SQL优化）
. 代码重构
. 新需求沟通

** 总结：
. 项目上线后提升该企业工作效率、简化订单流程、保证无错误拆单，极大提升客户公司业务能力
. 提升需求分析与团队管理能力
. 这是我第一次担任小组领导职务


* 2015年8月--2016年1月 数据管理项目 
** 项目背景：
. 解决电视台的日常文件安全管理 
. 局域网上传下载文件 
. 共享文件文件 
. 恶意文件识别 

** 角色：JAVA开发

** 内容：

. 后台DAO层负责My Batis、HDFS底层调用代码
. 后台business负责分享部分代码与数据加密代码 
. 后台service层负责分享、被分享、资料集编写
. 前台Controller中分享与被分享编写
. 前台页面负责分享、分享查看、分享预览、被分享部分功能实现
. 前台用到的技术：AJAX，Jquery,JavaScript,HTML5中视频、PDF、音频预览，前台分页
. 前台使用框架: semantic UI 
. 后台代码维护与前后台代码优化 
. 这个项目提升了团队工作能力、分布式文件理解能力、深化socket与HTTP协议理解、提升HTML与JavaScript能力

** 总结：

. 提升代码熟练程度
. 提升团队工作能力
. 这个项目是我第一次正式参加的项目，可以说对我职业生涯有极大的影响


* 教育经历

** 2011/09 - 2015/07   辽宁科技大学信息技术学院  网络工程   本科

* 兴趣爱好

   每当心情不好、或事业受挫就会去爬山，在山顶领略不一样的风景及体验整个过程。
   总体来说就是我的世界很小，需要去拓展。
