= k8s 安装

. 关闭交换内存
+
----
   sudo swapoff -a
   sudo editor /etc/fstab   # 注释 swap.img 行
   sudo rm -f /swap.img
----

. 安装containerd
+
----
sudo apt-get update &&\
sudo apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release &&\
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg &&\
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&\
sudo apt-get update &&\
sudo apt-get install  containerd.io -y

----

. 配置containerd
+
----
cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# Setup required sysctl params, these persist across reboots.
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# Apply sysctl params without reboot
sudo sysctl --system

containerd config default | sudo tee /etc/containerd/config.toml
----

. 配置 config.toml
+
----
endpoint加速器
    [plugins."io.containerd.tracing.processor.v1.otlp"]

          endpoint = "https://docker.mirrors.ustc.edu.cn/"

          insecure = false

          protocol = “"

修改sandbox_image
    #sandbox_image = "k8s.gcr.io/pause:3.6"

        sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9"

修改Systemdcgroup
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]

              IoUid = 0

              NoNewKeyring = false

              NoPivotRoot = false

              Root = ""

              ShimCgroup = ""

              SystemdCgroup = true

修改root和state的路径(看硬盘情况)
    required_plugins = []

    root = "/home/containerd/root"

    state = "/home/containerd/state"

    temp = ""

    version = 2
修改镜像代理
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = "https://docker.m.daocloud.io"]
----

. 重启container
+
----
systemctl restart containerd
----

. 加入仓库地址
+
----
   sudo apt-get update && sudo apt-get install -y apt-transport-https curl &&\
   curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg |sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k8s.gpg  && \
   echo "deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main" |sudo tee -a /etc/apt/sources.list.d/kubernetes.list
----

. 安装k8s
+
----
   sudo apt-get update && sudo apt-get install -y  kubeadm
----

.. 调整网络配置
+
----
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF
sudo bash -c "cat  > /etc/sysctl.d/k8s.conf" <<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
----


.. 初始化k8s
+
----
sudo kubeadm init \
--image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers \
--pod-network-cidr=172.18.0.0/16 \
--cri-socket=/run/containerd/containerd.sock \
--apiserver-advertise-address=172.16.2.189 \
-v=5
----


.. 给当前用户授权
+
----
   mkdir -p $HOME/.kube
   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   sudo chown $(id -u):$(id -g) $HOME/.kube/config
----

.. 启用主控机同时作为工作节点(可选)
+
----
老版本:
   kubectl taint nodes --all node-role.kubernetes.io/master-
新版本：
   kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-
----

.. 安装网络插件
+
----
   kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
   wget https://docs.projectcalico.org/manifests/custom-resources.yaml
   修改custom-resources.yaml中的ip 为-pod-network-cidr
   kubectl apply -f custom-resources.yaml
   watch kubectl get pods -n calico-system
----

. 生成token并加入集群
+
----
  kubeadm token create
  openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1
  kubeadm join 192.168.6.190:6443 --token 008qgs.lqe40icggq4npkny --discovery-token-ca-cert-hash sha256:e8cbe99a3b0e6afa4c3511d1daaaa836aed2422af0c5ddb31cb2d157b3270566
  也可以使用：
  sudo kubeadm token create --print-join-command
----

. 重置集群
+
----
sudo kubeadm reset -f
sudo rm -rf /etc/cni /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/run/kubernetes ~/.kube/*
sudo iptables -F && sudo  iptables -X
sudo iptables -t raw -F && sudo  iptables -t raw -X
sudo iptables -t mangle -F && sudo  iptables -t mangle -X
sudo iptables -t nat -F && sudo  iptables -t nat -X

sudo iptables-legacy -F && sudo  iptables-legacy -X
sudo iptables-legacy -t raw -F && sudo  iptables-legacy -t raw -X
sudo iptables-legacy -t mangle -F && sudo  iptables-legacy -t mangle -X
sudo iptables-legacy -t nat -F && sudo  iptables-legacy -t nat -X

sudo systemctl restart docker
----

. crictl 配置
+
....
nano /etc/crictl.yaml
....
+
....
runtime-endpoint: unix:///run/containerd/containerd.sock image-endpoint:
unix:///run/containerd/containerd.sock timeout: 5 debug: false

....

. ctr 自动补全配置
+
....
mkdir /etc/bash_completion.d nano /etc/bash_completion.d/ctr
....
+
....
_ctr() { local cur prev words cword opts _get_comp_words_by_ref -n : cur
    prev words cword opts=$(ctr --help | awk '/^\s+[a-z]/ {print $1}' | sed
    's/,$//')  # 移除逗号

    # 如果是第一个命令，补全主命令
    if [[ ${cword} == 1 ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    else # 针对特定子命令进行补全 case $prev in images) COMPREPLY=( $(compgen -W "list
        pull remove import export tag" -- $cur) ) ;; containers) COMPREPLY=(
        $(compgen -W "list create start stop delete" -- $cur) ) ;; *)
        COMPREPLY=( $(compgen -W "${opts}" -- $cur) ) ;; esac
    fi

    return 0
}

complete -F _ctr ctr
....