apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-registry-pv
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nas/data/registry
    server: dev
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-registry-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: registry
  template:
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      volumes:
        - name: data-registry
          persistentVolumeClaim:
            claimName: data-registry-pvc
      containers:
        - name: registry
          image: registry:2.7.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: data-registry
      
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
  externalIPs:
    - 192.168.1.131
  type: NodePort
    