apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /nas/gitlab/config
    server: dev
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /nas/gitlab/logs
    server: dev
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /nas/gitlab/data
    server: dev
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  serviceName: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      volumes:
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config-pvc
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs-pvc
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data-pvc
      containers:
        - name: gitlab
          imagePullPolicy: IfNotPresent
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 443
            - containerPort: 80
            - containerPort: 22
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab-config
            - mountPath: /var/log/gitlab
              name: gitlab-logs
            - mountPath: /var/opt/gitlab
              name: gitlab-data

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - port: 2443
      targetPort: 443
      name: https
    - port: 280
      targetPort: 80
      name: http
    - port: 222
      targetPort: 22
      name: ssh
  externalIPs:
    - 192.168.1.131
  type: NodePort

