apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-limit-job
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 10
  completions: 5
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
        - name: main
          image: luksa/batch-job
      restartPolicy: OnFailure