#基础镜像
FROM mysql:8.0.18
COPY my.cnf /etc/mysql/my.cnf
COPY my_mgr_single.cnf /etc/mysql/conf.d/mysql.cnf
COPY sql_mgr_init.sql /docker-entrypoint-initdb.d/sql_mgr_init.sql
#环境变量
ENV MYSQL_ROOT_PASSWORD=xiefei

#命令
CMD ["mysqld"]
