#基础镜像
FROM mongo:4.2.2

# ENV MONGO_INITDB_ROOT_USERNAME=root
# ENV MONGO_INITDB_ROOT_PASSWORD=xiefei
# COPY mongod_cluster.yml /etc/mongo/mongod.yml
# COPY ./test/certificate.pem /data/configdb/certificate.pem
# COPY ./tls/* /data/configdb/

#命令
# CMD ["mongod","--config","/etc/mongo/mongod.yml"]
CMD [ "mongod" ]