version: "3.7"
services: 
  mongosingle:
    image: mongo:4.2.2
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xiefei
    volumes: 
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks: 
      net-mongo:
        aliases: 
          - mongo-single
    hostname: mongo-single
  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: xiefei
      ME_CONFIG_MONGODB_SERVER: mongo-single
    networks: 
      net-mongo:
networks: 
  net-mongo:
    driver: bridge
    name: net-mongo
volumes:
  mongodb:
    name: mongodb
  mongoconfig:
    name: mongoconfig
  